### ISSUE TITLE
KeyError: 'EpCost'  cannot run the uodate() function

### ISSUE THREAD

**Issue by lalala215** [akjayant/PPO_Lagrangian_PyTorch#1]
hi, this code does not have the ‘EpCost’ in the logger. 
So It can not run the update() function. 

```
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1491, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "ppo.py", line 488, in <module>
    logger_kwargs=logger_kwargs)
  File "ppo.py", line 444, in ppo
    update()
  File "ppo.py", line 324, in update
    cur_cost = logger.get_stats('EpCost')[0]
  File "/Demo/PPO_Lagrangian_PyTorch-main/utils/logx.py", line 381, in get_stats
    v = self.epoch_dict[key]
KeyError: 'EpCost'
```

**Comment by lalala215** [comment]
I figure out it. I forget to revise the max_ep_len. If I set 100 for max_ep_len, then is ok.
